### ISSUE TITLE
Query about QTL aggregation approach in manuscript

### ISSUE THREAD

**Issue by Al-Murphy** [yakirr/sldp#13]
Apologies but I'm posting here the question I sent to the corresponding email from your SLDP manuscript as I think this might be a more appropriate place for the discussion.

I am looking to apply SLDP to my own research and I have a query regarding theorem 8 in the [text](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6202062/). You specify the method by which you aggregate SNP information in the QTL studies so there is just one value per SNP (similar to GWAS summary statistics):

![image](https://user-images.githubusercontent.com/62257358/237034651-3ce5c3fa-ac15-4b81-a2d1-ddd0784b3f0e.png)

I understand the premise of summing all the marginal correlations of the SNP-gene interactions in the QTL study but why do you opt to divide this by the square root of the number of interactions rather than just the number of interactions (giving the mean)? Secondly, are these marginal correlations mentioned just the effect sizes (beta or z-score) from the QTL without any other preprocessing before passing to SLDP? Can either the z-score or beta value be used?

Thanks!
Alan.

**Comment by yakirr** [comment]
Hi Alan,

Unfortunately I worry that the email address listed on the paper is no longer functioning so I did not receive your email -- I apologize for that! Here are the answers to your question:
1) The marginal correlations are the effect sizes (betas, not z-scores) without any pre-processing. Since this is a pretty empirical procedure, z-scores should work as well -- within a single study the z-scores approximately equal a scaled version of the betas.
2) The reason for dividing by the square root of |G_m| is that assuming independence of genes this is equivalent to a z-score testing whether SNP m has a non-zero effect on expression of it's nearby genes on average. Another way to think of this is that if you divide by |G_m| then an expression-increasing SNP near 100 genes and an expression-increasing SNP near 2 genes would be weighted equally even if there's a lot more evidence that the former is expression-increasing. If you divide by the square root of |G_m|, then the former gets a much higher score, consistent with the fact that there's more evidence showing that it's expression-increasing. But there's nothing about the subsequent analyses that relies on this characterization and genes aren't independent anyway, so in a sense this was just an aesthetically inoffensive way to make an arbitrary choice about how to combine these numbers.

Does this clarify?
Yakir

**Comment by Al-Murphy** [comment]
That makes a lot of sense, thanks for this!

**Comment by Al-Murphy** [comment]
Hey @yakirr 

I just noted that when I tried the approach above with the beta value in the QTL set I get the following error:

```
Traceback (most recent call last):
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/bin/sldp", line 379, in <module>
    preprocess_sumstats(args)
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/bin/sldp", line 255, in preprocess_sumstats
    sldp.preprocesspheno.main(args_)
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/lib/python2.7/site-packages/sldp/preprocesspheno.py", line 25, in main
    ss = ss[ss.Z.notnull() & ss.N.notnull()]
  File "/rds/general/user/aemurphy/home/anaconda3/envs/sldp/lib/python2.7/site-packages/pandas/core/generic.py", line 5067, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'DataFrame' object has no attribute 'Z'
```

It appears the preprocess SLDP script expects a Z value rather than a Z or beta. Am I right to say I can just rename the beta column as Z before passing the QTL set to SLDP?
