### ISSUE TITLE
ValueError: There should be no nans in the postprocessed annotation. But there are 9886

### ISSUE THREAD

**Issue by AbbyD99** [yakirr/sldp#4]
hi,

I got "ValueError: There should be no nans in the postprocessed annotation. But there are 9886" when running final sldp. But I checked my RV.gz file, there are no nans. I wonder what's the problem here, and how can I fix it. 

Abby

**Comment by yakirr** [comment]
Hi Abby,

Can you run `import pandas as pd; df = pd.read_csv(filename, sep='\t'); np.isnan(df.annotname).sum()` to confirm that pandas agrees with you that there are no nans? Sometimes pandas gets confused by, e.g., numbers with too many digits.

Keep me posted,
Yakir

**Comment by AbbyD99** [comment]
Hi yakir,

I did what you suggested, there are no nans. I read the code in sldp, I think the problem is the maf5 backgroundannots I used, I think it's not for the EAS since the snps are not the same with my RV.gz and ref bim file. Can you tell me how to make the EAS backgroundannots in maf5?

Abby

**Comment by yakirr** [comment]
Hi Abby,

Sorry for the delay. To make the background annots for EAS, you need to create files analogous to the `*.sannot` files in [https://storage.googleapis.com/broad-alkesgroup-public/SLDP/background/maf5.tar.gz](https://storage.googleapis.com/broad-alkesgroup-public/SLDP/background/maf5.tar.gz). Here's how you would do it using the KG3 reference genome available on the sldp website. You can hopefully adapt these instructions to your EAS reference genome and SNPs that you're using.
1. Download the [https://storage.googleapis.com/broad-alkesgroup-public/SLDP/refpanel/KG3.tar.gz](full reference genome) (not just HM3 SNPs).
2. For each chromosome, and for each SNP, obtain the BP location, the location in centimorgans, the rsid, and the reference and alternate alleles. These can be gathered (e.g., for chromosome 22 for EUR) from the file `1000G.EUR.QC.22.bim`.
3. For each SNP, compute its minor allele frequency using plink.
4. For each SNP m, compute the quantities u^i_m defined in the [https://www.nature.com/articles/s41588-018-0196-7#Sec10](sldp publication) for i=1,...,5 (equation reproduced below; we use alpha_s = -0.3):
![image](https://user-images.githubusercontent.com/3740601/142660654-4fd99005-199c-4367-8ea4-e47dabf39c5d.png)
5. Create, in the case of chromosome 22, the file `22.sannot` to contain one line per SNP with the following information: chromosome number, BP location, rsid, location in centimorgans, alternate allele, reference allele, u1^1, u^2, u^3, u^4, u^5. See below for an example of the header of this file and a sample line for the KG3 EUR reference.
```
CHR	BP	SNP	CM	A1	A2	minor1	minor2	minor3	minor4	minor5
22	16051249	rs62224609	-0.00094708154	C	T	0.0	0.0	0.532748634113	0.0	0.0
```
Note that the alleles of each SNP should appear here in the same order that they appear in the `.bim` file from your reference genome.
6. Process this resulting `.sannot` files the way you would [https://github.com/yakirr/sldp/wiki/Preprocessing-instructions](process any other signed functional annotation).

I hope this helps. Let me know if you have other questions!

**Comment by AbbyD99** [comment]
hi yakirr,

I wannna know what's the meaning of 1{MAFm is in ith quintile}, how should I compute it ?

abby

**Comment by yakirr** [comment]
It equals 1 if the MAF of SNP m in is in the i-th quintile and 0 otherwise. Does that clarify?

**Comment by AbbyD99** [comment]
hi yakirr,

Really thanks for the patience.

I wonder how do you determine SNP m is in the i-th quintile? I checked the file, for example
` CHR           SNP   A1   A2          MAF  NCHROBS`
`22   rs587616822    G    C      0.02147      978`
`22    rs62224609    C    T        0.091      978`
`22   rs587646183    C    T      0.02658      978`

`CHR BP	SNP	CM	A1	A2	minor1	minor2	minor3	minor4	minor5`
`22      16050840        rs587616822     -0.0048996974   G       C       0.0     0.0     0.0     0.0     0.0`
`22      16051249        rs62224609      -0.00094708154  C       T       0.0     0.0     0.532748634113  0.0     0.0 `
`22      16052463        rs587646183     0.010833912     C       T       0.0     0.354698893006  0.0     0.0     0.0`

when maf equals 0.02147 minor1-5 are all zero(why?). when maf equals 0.091, minor2 equals 0.532748634113, so 0.091 is in the 2-th quintile? Why? Also, 0.532748634113 is not equal to sqrt(2*0.091*(1-0.091)^0.7).

**Comment by yakirr** [comment]
Hi Abby,

1) I believe (but don't fully remember) that we set very low MAF SNPs
to not be included in any of the MAF bins as a QC measure. But it may take
me some weeks to verify this on my own, unfortunately, because of issues
accessing the scripts.
2) MAF bins are defined based on percentiles, not the absolute MAF. So
although MAF of 0.091 is <10%, if it is higher than the MAFs of 20% of the
SNPs then it would land this SNP in the second MAF quintile.
3) Let me check on the equation and get back to you.

You could check the minimal and maximal MAF of the SNPs in each MAF bin in
that file and also the minimal and maximal MAF of the SNPs that have all 0s?

**Comment by AbbyD99** [comment]
Hi yakirr,

Have you checked on the script and the equation? I tried to ignore the parameter --background-sannot-chr, but it gives me an error below, I don't know if it's because the background sannot.
 
53.95844316482544 : loading chr 22 of range(1, 23)
15557 snps in refpanel 6 columns, including metadata
reading sumstats
2467 sumstats nans out of 15557
reading annotations
54.33127570152283 : reading annot signed_annotation/
adding ['introgressed.R']
jackknifing
/home/tangdie/anaconda3/lib/python3.8/site-packages/sldp/chunkstats.py:14: RuntimeWarning: invalid value encountered in double_scalars
  avgldblocksize = totalM / (ldblocks.M_H != 0).sum()
0 introgressed.R
Traceback (most recent call last):
  File "/home/tangdie/anaconda3/bin/sldp", line 382, in <module>
    main(args)
  File "/home/tangdie/anaconda3/bin/sldp", line 159, in main
    mu = cs.get_est(sum(chunk_nums), sum(chunk_denoms), k, len(background_names))
  File "/home/tangdie/anaconda3/lib/python3.8/site-packages/sldp/chunkstats.py", line 59, in get_est
    num = num[ind]
TypeError: 'int' object is not subscriptable

**Comment by yakirr** [comment]
Hi Abby,

I apologize for the delay -- I turn out to have lost access to the
computing cluster where the script in question is stored. I didn't consider
it part of the sldp method and so it's not on the sldp github; and I didn't
consider it part of any individual analysis for the paper, so it's not on
the sldp-display github. I'm working to see if I can re-gain access to the
code in order to clarify what's going on.

Without the code, I can though still address one of your questions
directly. You asked "when maf equals 0.091, minor2 equals 0.532748634113,
so 0.091 is in the 2-th quintile? Why? Also, 0.532748634113 is not equal to
sqrt(2*0.091*(1-0.091)^0.7)." The answer to the last question is that
0.532748634113 equals sqrt(2**0.091**(1-0.091))^0.7 rather than sqrt(2
*0.091*(1-0.091)^0.7). I.e., the (1+\alpha_s) should be outside the
square-root rather than inside it. I apologize for that typo!

So I think between this and my previous response the main open issue is why
some SNPs have values of 0 for maf1 through maf5.

In the meantime, I would not recommend running sldp without a
background-sannot -- as you're seeing, the code hasn't really been tested
in that way and I don't think the results would be legitimate. If you're
very eager to move forward, I would either make your own 5-maf-bin
background annotation in any way you see fit -- it shouldn't actually
matter too much what numbers you assign the SNPs; the important thing is to
give SLDP the flexibility to model MAF-dependent effects with enough
granularity (i.e., but giving it 5 distinct MAF bins). If you'd like to do
something even simpler, you could make a single background annotation where
every SNP is given a value of 1; that should allow the code to run, but I
don't know how much stock I'd put in the results.

Hope this helps, and sorry for the delay!
Yakir

**Comment by yakirr** [comment]
Abby,

I was able to locate the relevant script. The reason some SNPs have values of 0 is not about the MAF of those SNPs. Rather, it's because those SNPs are "[strand-ambiguous](https://www.biostars.org/p/375143/)", i.e., their alleles are both either G/C or A/T.. For these SNPs, a GWAS would need to specify not only what allele is the reference allele but also which strand that allele is on. Because such information is difficult to gain, all sldp annotations zero out these SNPs and essentially ignore them.

You can download [the script](https://www.dropbox.com/s/ouekfle58qq03zp/make_background.py?dl=1) for creating the minor allele-based annotations, along with [an example of how to execute it](https://www.dropbox.com/s/e329bkbzojqlm3d/make_maf5.sh?dl=1). The script requires some python packages, including [ypy](https://github.com/yakirr/ypy) and [gprim](https://github.com/yakirr/gprim), which you can clone into your PYTHONPATH, as well as pybedtools and pysnptools, which you can pip install. Sorry I wasn't able to locate this file for you sooner!

Does this address your issue?

Warmly,
Yakir

**Comment by AbbyD99** [comment]
Hi, Yakir

Thanks for the reply, it did help me to create the back annotation for EAS, much thanks! However, when I run the final processing command, it reports errors below which I cannot find the reason for. Can you help me?

jackknifing
/home/tangdie/anaconda3/lib/python3.8/site-packages/sldp/chunkstats.py:14: RuntimeWarning: invalid value encountered in double_scalars
avgldblocksize = totalM / (ldblocks.M_H != 0).sum()
0 introgressed.R
Traceback (most recent call last):
File "/home/tangdie/anaconda3/bin/sldp", line 382, in
main(args)
File "/home/tangdie/anaconda3/bin/sldp", line 159, in main
mu = cs.get_est(sum(chunk_nums), sum(chunk_denoms), k, len(background_names))
File "/home/tangdie/anaconda3/lib/python3.8/site-packages/sldp/chunkstats.py", line 59, in get_est
num = num[ind]
TypeError: 'int' object is not subscriptable

**Comment by yakirr** [comment]
Hmm.. could you send a) the file where you define the LD blocks, and b) the
command you ran and the complete output that resulted?

**Comment by yakirr** [comment]
Hi Abby, sorry for the delay here -- I'd responded by email but somehow the response didn't make it to here. Unfortunately, I think that with a p-value of 0.64 it will be hard for you to count on finding confirmatory evidence since this result seems far from statistical significance. (Unless that was a typo.) I don't know of any other method that tries to do the same thing sldp does. Though you could imagine others, e.g., based on fine mapped associations.

**Comment by yakirr** [comment]
Hi Abby,

Unfortunately, I think that with a p-value of 0.64 it will be hard for you
to count on finding confirmatory evidence since this result seems far from
statistical significance. Unless that was a typo?

I don't know of any other method that tries to do the same thing sldp does.
(Though you could imagine others, e.g., based on fine mapped associations.)

Warmly,
Yakir
