### ISSUE TITLE
Some questions about data preprocessing 

### ISSUE THREAD

**Issue by liqingbioinfo** [yakirr/sldp#8]
Hi Yakir
    
     I'm asking some questions about data preprocessing here as our messages may be helpful to those who have similar problems in data preprocessing. 
     My first question is should I normalize singed functional annotations? I noticed that most of the singed values in your example IRF1 annotation were pretty small. Are these raw outputs of Basset software? Most of my functional values range from -1 to 1 and there are some extremely large values, e.g., -10 or 10. Do you have any suggestions for that? 
      My second question is about the preprocessing of summary statistics. Why do we use KG3.tar.gz in preprocessing while we use KG3.hm3.tar.gz in the final sldp analysis? Will SNPs in 1000G_hm3_noMHC.rsid file be used in sldp analysis? As for GTEx tissues, would you recommend using Pre-processed summary statistics or Residualized versions from your data (https://data.broadinstitute.org/alkesgroup/SLDP/sumstats/molecular_gtexv7_tissues/)
       I really appreciate your help and answers. 

Best regards
Leah

**Comment by yakirr** [comment]
Hi Leah,

Here are the answers to your questions:
1. The linear scaling of your annotations doesn't matter. E.g., if you multiply everything in your annotation by 2 you will get identical results from SLDP. However, it sounds like your annotations may also have some extreme values, which is a more difficult question: because SLDP assumes a polygenic model, it won't be able to detect signals that are driven by a very small number of SNPs so if your annotation has, say, most SNPs assigned very small values and then a small number of SNPs with very large values then SLDP will not be very well powered. So it may be a good idea to take your very large values and "force" them to smaller ones. (Of course, it could be that the underlying biology is such that truly only a small number of SNPs explain your signal; in this case, SLDP is probably not the best tool.)
2. The reason that there are different sets of SNPs used in different parts of SLDP is that SLDP accounts for untyped causal SNPs. It does this by using the reference panel LD between the untyped causal SNPs and the typed SNPs. So yes, the full set of KG3.tar.gz SNPs is relevant and the values you assign in your annotation to those SNPs do matter. But then you only need summary statistics for the smaller set of KG3.hm3.tar.gz SNPs.
3. I didn't understand your question about the GTEx analysis. Could you try asking it in a different way?

I hope this helps!
Yakir

**Comment by liqingbioinfo** [comment]
Hi Yakir
    
    I really appreciate your detailed replies. They are quite illustrative!
    I'm grateful to learn that SLDP may not be the best tool when there are only a small number of signal SNPs. I don’t think that’s my case. However, I do have the problem of outliers in my functional scores and I will force them to be smaller based on your suggestions.
    For the GTEx data, I wonder should I use the pre-processed summary statistics or the residualized version of them. What’s the difference between pre-processed and residualized versions? This question comes from the following sentences written on your Data page (https://github.com/yakirr/sldp/wiki/Data), Phenotype section: "Pre-processed summary statistics for eQTLs from each of the 48 GTEx tissues analyzed in Reshef et al. 2018. Residualized versions of these summary statistics are also available, in which we condition on average eQTL effects across all 48 tissues."
    I highly appreciate your help and look forward to your answers in advance.

Yours sincerely
Leah

**Comment by liqingbioinfo** [comment]
Hi Yakirr
    
    You answered my questions very clearly! That's a great support to me! I couldn’t run SLDP on my functional data without your help! 
    May I ask you two more questions related to SLDP results? Shall I focus on the z-score or rf (functional correlation)? For example, I got z=1.51 and rf=0.22 for one set of function scores. For another set of functional scores, I got z=1.69 and rf=0.20. Can I say the former set scores have a slightly higher functional correlation to my phenotype? How about cases when rf is negative? Does that mean singed scores lead to another direction of phenotype? 
    Thank you again and hope these are all my questions! 

Yours sincerely
Leah
